;;Tally.ERP 9 workstation specific parameters file
[TALLY]

;;** Gateway server configuration, 
;; ** Tally Gateway Server=server:port
Tally Gateway Server=Server:9999

;;Specify list of TDL files for user defined reports and changes, 
;; ** TO STOP LOADING TDL FILES, set the following line to NO
User TDL=Yes
TDL=D:\TALLY.ERP9\dairy.tcp

;;Specify the path of Capsule Folder
Capsule=

;;Specify the path of Local Help Folder
Help=D:\Tally.ERP1\help

LicTimeout=

;;Specify list of companies to preload, 
;; ** TO STOP DEFAULT LOADING set the following line to NO
Default Companies=No
Load=10000

;;Specify the list of gold gateway servers to subscribe
Tally Gold License Server=

;;Specify location of Data files
Data=\\Server\e\DATA\TD

Client Server=None
ServerPort=9999
Enable ODBC Server=No
Load Buffering=No
Ignore Tcp Timeout=Yes

AutoInstallNumber=

;;Specify location of TALLYSAV.tsf (saved configuration of Tally)
Config=D:\Tally.ERP9

;;Specify location of Language Files
LangPath=D:\Tally.ERP9\Lang

;;Specify location where files are created during export by default
Export Path=D:\Tally.ERP9

;;Specify Color details of local monitor
Color=Yes
Sound=No

Width=1918
Height=1038
